### PR TITLE
added Linux as a supported platform

### PR DESCRIPTION
**Pull request by gaktive**
May need to figure out an updated diagram since the Linux reference inside the macos bit is specific to Lima.

Signed-off-by: Gary A Korhonen <gkorhonen@suse.com>

### CODE REVIEW

**Comment by gaktive** [comment]
Supports part of https://github.com/rancher-sandbox/rancher-desktop/issues/786

**Comment by gaktive** [comment]
@simonflood I believe I already have taken care of what you have suggested in #9. Does this look all right to you? If so, I can close your item as a duplicate and we can get this change in, whilst I look at other updates.

**Comment by simonflood** [comment]
Thanks. I also added Linux to the How it Works section - that's not covered by #9

**Comment by gaktive** [comment]
Closing in light of #9

**Pull request closed without merging**
